# ç½‘ç«™æ ‡é¢˜
logo_title: ä¸ªäººåšå®¢
# åˆå§‹åŒ–é£æ ¼ black/light
style: light

#SEOä¼˜åŒ–

## ç½‘ç«™æè¿°
description: æ¬¢è¿è®¿é—®ï¼

## ç½‘ç«™å…³é”®è¯ï¼šç”¨è‹±æ–‡é€—å·åˆ†å‰²
keywords: Blog,Hexo,Theme,åˆ˜å®ç”Ÿ

# é¦–é¡µURL
link: https://www.liuxunzhuo.top

#æ ‡è¯­:
words: Blog ğŸ¤–ï¸ GitHub Pages ğŸ§‘â€ğŸ’» Life ğŸŒˆ

# ä½ çš„æ˜µç§°
author: bcv
# ä¸­å¿ƒå›¾æ ‡é€‰æ‹©ç”·å¥³æˆ–è€…è‡ªå®šä¹‰
gender: /img/male.png #/img/female.png

favicon: /img/favicon.ico

# èœå•æ é…ç½®
menu:
  # å…³äºæˆ‘ğŸ‘€: /about
  # è®¿é—®ä¸»ç«™ğŸ‰: https://liuxunzhuo.tech
  GitHubğŸ’: https://github.com/LiuIos

# åšäº†åŸŸåé™åˆ¶ï¼Œè¯·æ”¹æˆè‡ªå·±çš„ KEY
# è‹¥å…³é—­valine è®¾ç½®enableä¸ºfalseâˆ‚
valine:
  enable: true
  appId: ODBJnxOXlHO3QooAbKpprTQF-gzGzoHsz
  appKey: l0E6n9ofbixyqyFBJUajeFU0

highlight:
  enable: true
